import test from "node:test";
import assert from "node:assert/strict";

test("fill-team-test-name", (t) => {
    pokemonTeamArray = [null, null, null, null, null, null];
    const test1 = "Volcarona";
    const test2 = "Fuecoco";
    const test3 = "Wooper (Paldea)";
    const test4 = "Sylveon";
    const test5 = "Zoroark";
    const test6 = "Chandelure";
    validatePokemon(test1, 1);
    validatePokemon(test2, 2);
    validatePokemon(test3, 3);
    validatePokemon(test4, 4);
    validatePokemon(test5, 5);
    validatePokemon(test6, 6);
    const res1 = pokemonTeamArray[0].name === test1;
    const res2 = pokemonTeamArray[1].name === test2;
    const res3 = pokemonTeamArray[2].name === test3;
    const res4 = pokemonTeamArray[3].name === test4;
    const res5 = pokemonTeamArray[4].name === test5;
    const res6 = pokemonTeamArray[5].name === test6;
    const result = res1 && res2 && res3 && res4 && res5 && res6;
    assert.equal(result, true, "Error in name insertion in pokemonTeamArray");
});
test("fill-team-test-type", (t) => {
    pokemonTeamArray = [null, null, null, null, null, null];
    const test1 = "Volcarona";
    const test2 = "Fuecoco";
    const test3 = "Wooper (Paldea)";
    const test4 = "Sylveon";
    const test5 = "Zoroark";
    const test6 = "Chandelure";
    validatePokemon(test1, 1);
    validatePokemon(test2, 2);
    validatePokemon(test3, 3);
    validatePokemon(test4, 4);
    validatePokemon(test5, 5);
    validatePokemon(test6, 6);
    const res11 = pokemonTeamArray[0].type1 === "bug";
    const res12 = pokemonTeamArray[0].type2 === "fire";
    const res1 = res11 && res12;
    const res21 = pokemonTeamArray[1].type1 === "fire";
    const res22 = pokemonTeamArray[1].type2 === null;
    const res2 = res21 && res22;
    const res31 = pokemonTeamArray[2].type1 === "poison";
    const res32 = pokemonTeamArray[2].type2 === "ground";
    const res3 = res31 && res32;
    const res41 = pokemonTeamArray[3].type1 === "fairy";
    const res42 = pokemonTeamArray[3].type2 === null;
    const res4 = res41 && res42;
    const res51 = pokemonTeamArray[4].type1 === "dark";
    const res52 = pokemonTeamArray[4].type2 === null;
    const res5 = res51 && res52;
    const res61 = pokemonTeamArray[5].type1 === "ghost";
    const res62 = pokemonTeamArray[5].type2 === "fire";
    const res6 = res61 && res62;
    const result = res1 && res2 && res3 && res4 && res5 && res6;
    assert.equal(result, true, "Error in type insertion ini pokemonTeamArray");
});
test("test-duplicate-elements", (t) => {
    pokemonTeamArray = [null, null, null, null, null, null];
    const test1 = "Ditto";
    validatePokemon(test1, 1);
    validatePokemon(test1, 2);
    validatePokemon(test1, 3);
    validatePokemon(test1, 4);
    validatePokemon(test1, 5);
    validatePokemon(test1, 6);
    const res11 = pokemonTeamArray[0].name === "Ditto";
    const res12 = pokemonTeamArray[0].type1 === "normal";
    const res13 = pokemonTeamArray[0].type2 === null;
    const res1 = res11 && res12 && res13;
    const res2 = pokemonTeamArray[1] === null;
    const res3 = pokemonTeamArray[2] === null;
    const res4 = pokemonTeamArray[3] === null;
    const res5 = pokemonTeamArray[4] === null;
    const res6 = pokemonTeamArray[5] === null;
    const result = res1 && res2 && res3 && res4 && res5 && res6;
    assert.equal(result, true, "Error: insertion of duplicate elements in pokemonTeamArray");
    //this error message can be wrong in case what fails is the first element but if the error message gets thrown it will be checked regardless so it will be noticed
});
test("test-wrong-names", (t) => {
    pokemonTeamArray = [null, null, null, null, null, null];
    const test1 = "Pichaku";
    const test2 = "Puchiko";
    const test3 = "Puccia";
    const test4 = "Boccia";
    const test5 = "Pukicho";
    const test6 = "Popipo";
    validatePokemon(test1, 1);
    validatePokemon(test2, 2);
    validatePokemon(test3, 3);
    validatePokemon(test4, 4);
    validatePokemon(test5, 5);
    validatePokemon(test6, 6);
    const res1 = pokemonTeamArray[0] === null;
    const res2 = pokemonTeamArray[1] === null;
    const res3 = pokemonTeamArray[2] === null;
    const res4 = pokemonTeamArray[3] === null;
    const res5 = pokemonTeamArray[4] === null;
    const res6 = pokemonTeamArray[5] === null;
    const result = res1 & res2 & res3 & res4 & res5 & res6;
    assert.equal(result, true, "Error: insertion of wrong values");
});
//this was supposed to be misspelled names but ironically i am not sure of its spelling right now and i don't want to look it up